### ISSUE TITLE
Disk not recognized

### ISSUE THREAD

**Issue by cscd98** [wmchris/DellXPS15-9560-OSX#1]
Hi,

I followed the guide(s) and created my installer. Unfortunately the disk is not recognized in the installer.

Here is my ACPI ID of the Toshiba NVMe SSD in my 9560 (4k, 16GB):

\_SB.PCI0.RP09.PXSX

Also, I am using BIOS 1.2.4.

**Comment by krim404** [comment]
did you switch to AHCI mode in bios? Most people with your issue tend to forget this step.

**Comment by cscd98** [comment]
@wmchris Yes it's in AHCI mode. I also changed the disk to 4k sectors using Ubuntu

**Comment by krim404** [comment]
did you remove the patches from the config.plist regarding NVME hackr?

From the 4k tutorial: `Now remove SSDT-Hackr.aml from EFI/ACPI/patched, the hackrnvmefamily kext or the clover storage hotpatches from your EFI bootloader and reinstall OSX)`

If any of them are present, then the disk will not show up.

**Comment by cscd98** [comment]
@wmchris No I didn't. I mounted the EFI and removed SSDT-Hackr.xml and hackr kext and loaded up my 9560. Still didn't recognize the NVMe

**Comment by krim404** [comment]
you should not have a hackr kext in the installation. The config contains hotpaches. Remove them.

**Comment by cscd98** [comment]
@wmchris Hi, I tried without the hackr kext and SSDT-Hackr.xml and it was not recognized.

Regarding your guide - "Overwrite everything in the CLOVER folder of the partition EFI with the content of ./10.12/CLOVER." Does that mean replace files or merge and replace?

**Comment by krim404** [comment]
merge replace. see the command.
as i said: config.plist contains hotpatches! In the installation you should never have a hackr kext.
