### ISSUE TITLE
Experiences

### ISSUE THREAD

**Issue by TomFreudenberg** [wmchris/DellXPS15-9560-OSX#10]
Hi @wmchris 

could you please step out some experiences about working with OSX on a Dell?

I have an old Mac Pro Late 2012 and was waiting for the new 32GB Ram Macs. In case that those will not arrive before end of 2018 I am thinking about running hackintosh.

I have bought a 32GB Dell 9560 as well early this year, running linux on it.

For my job I need OSX and so I am wondering if you could gave me some of your experiences with the hackintosh on that device.

Thanks for your answer in advance
Tom

**Comment by krim404** [comment]
works pretty well. very much llike on a real mac.

**Comment by TomFreudenberg** [comment]
Hi Chris

Thanks for your response, so I will try it myself.

Cheers
Tom

________________________________

Thomas Freudenberg
4commerce technologies AG
via mobile device

Am 11.11.2017 07:30 schrieb wmchris <notifications@github.com>:

works pretty well. very much llike on a real mac.
