### ISSUE TITLE
compatibility

### ISSUE THREAD

**Issue by ghost** [wmchris/DellXPS15-9560-OSX#4]
Hi Wmchris,

Thanks for your files,

I have the new dell XPS 9560 4k version, 16gb, 512 SSD, GTX 1050 4GB, I7.

I would like to know if the files that you give in this guide is EXACTLY the same as my config ?

If this is the case could you tell me if i take the 9550 files from the guide and replacd with this files and run it everything should run smootly no ?

Thanks for your time

Cheers Michael

**Comment by krim404** [comment]
issue reports are not for personal usage help. if you need help and tutorials, go to forums like insanelymac.com
